services:
  rds:
    image: 975050280865.dkr.ecr.eu-central-1.amazonaws.com/project/rds:latest
    container_name: rds
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis:
    image: 975050280865.dkr.ecr.eu-central-1.amazonaws.com/project/redis:latest
    container_name: redis
    restart: always
    ports:
      - "8001:6379"
    env_file:
      - .env