version: '3'
services:
  redis:
    image: 'redis'
    environment:
      REDIS_URL: "redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"

  backend-rds:
    build:
      context: ./backend_rds
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  backend-redis:
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    env_file:
      .env
    ports:
      - "6379:6379"



volumes:
  data:

