services:
  rds:
    image: 975050280865.dkr.ecr.eu-central-1.amazonaws.com/rds
    container_name: rds
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_rds.settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  redis:
    image: 975050280865.dkr.ecr.eu-central-1.amazonaws.com/redis
    container_name: redis
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_redis.settings
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}